// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: richer/BusinessMsg.proto

package cn.zjnktion.richer.core.protobuf;

public final class BusinessMsg {
  private BusinessMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code RequestType}
   */
  public enum RequestType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>REQUEST_LOGIN = 0;</code>
     */
    REQUEST_LOGIN(0),
    /**
     * <code>REQUEST_REGISTER = 1;</code>
     */
    REQUEST_REGISTER(1),
    /**
     * <code>REQUEST_HEARTBEAT = 2;</code>
     */
    REQUEST_HEARTBEAT(2),
    /**
     * <pre>
     * 有待扩展
     * </pre>
     *
     * <code>REQUEST_LOGOUT = 3;</code>
     */
    REQUEST_LOGOUT(3),
    ;

    /**
     * <code>REQUEST_LOGIN = 0;</code>
     */
    public static final int REQUEST_LOGIN_VALUE = 0;
    /**
     * <code>REQUEST_REGISTER = 1;</code>
     */
    public static final int REQUEST_REGISTER_VALUE = 1;
    /**
     * <code>REQUEST_HEARTBEAT = 2;</code>
     */
    public static final int REQUEST_HEARTBEAT_VALUE = 2;
    /**
     * <pre>
     * 有待扩展
     * </pre>
     *
     * <code>REQUEST_LOGOUT = 3;</code>
     */
    public static final int REQUEST_LOGOUT_VALUE = 3;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static RequestType valueOf(int value) {
      return forNumber(value);
    }

    public static RequestType forNumber(int value) {
      switch (value) {
        case 0: return REQUEST_LOGIN;
        case 1: return REQUEST_REGISTER;
        case 2: return REQUEST_HEARTBEAT;
        case 3: return REQUEST_LOGOUT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<RequestType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        RequestType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<RequestType>() {
            public RequestType findValueByNumber(int number) {
              return RequestType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return BusinessMsg.getDescriptor().getEnumTypes().get(0);
    }

    private static final RequestType[] VALUES = values();

    public static RequestType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private RequestType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:RequestType)
  }

  /**
   * Protobuf enum {@code ResponseType}
   */
  public enum ResponseType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>RESPONSE_LOGIN = 0;</code>
     */
    RESPONSE_LOGIN(0),
    /**
     * <code>RESPONSE_REGISTER = 1;</code>
     */
    RESPONSE_REGISTER(1),
    /**
     * <code>RESPONSE_HEARTBEAT = 2;</code>
     */
    RESPONSE_HEARTBEAT(2),
    /**
     * <code>RESPONSE_LOGOUT = 3;</code>
     */
    RESPONSE_LOGOUT(3),
    /**
     * <pre>
     * 有待扩展
     * </pre>
     *
     * <code>RESPONSE_DUPLICATE_LOGIN = 4;</code>
     */
    RESPONSE_DUPLICATE_LOGIN(4),
    ;

    /**
     * <code>RESPONSE_LOGIN = 0;</code>
     */
    public static final int RESPONSE_LOGIN_VALUE = 0;
    /**
     * <code>RESPONSE_REGISTER = 1;</code>
     */
    public static final int RESPONSE_REGISTER_VALUE = 1;
    /**
     * <code>RESPONSE_HEARTBEAT = 2;</code>
     */
    public static final int RESPONSE_HEARTBEAT_VALUE = 2;
    /**
     * <code>RESPONSE_LOGOUT = 3;</code>
     */
    public static final int RESPONSE_LOGOUT_VALUE = 3;
    /**
     * <pre>
     * 有待扩展
     * </pre>
     *
     * <code>RESPONSE_DUPLICATE_LOGIN = 4;</code>
     */
    public static final int RESPONSE_DUPLICATE_LOGIN_VALUE = 4;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static ResponseType valueOf(int value) {
      return forNumber(value);
    }

    public static ResponseType forNumber(int value) {
      switch (value) {
        case 0: return RESPONSE_LOGIN;
        case 1: return RESPONSE_REGISTER;
        case 2: return RESPONSE_HEARTBEAT;
        case 3: return RESPONSE_LOGOUT;
        case 4: return RESPONSE_DUPLICATE_LOGIN;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ResponseType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ResponseType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ResponseType>() {
            public ResponseType findValueByNumber(int number) {
              return ResponseType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return BusinessMsg.getDescriptor().getEnumTypes().get(1);
    }

    private static final ResponseType[] VALUES = values();

    public static ResponseType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ResponseType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:ResponseType)
  }

  public interface RequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Request)
      com.google.protobuf.GeneratedMessageV3.
          ExtendableMessageOrBuilder<Request> {

    /**
     * <code>optional .RequestType request_type = 1;</code>
     */
    boolean hasRequestType();
    /**
     * <code>optional .RequestType request_type = 1;</code>
     */
    RequestType getRequestType();

    /**
     * <pre>
     * 业务明文传输的一个标识用户在这台设备验证了登录信息的token，每次登录都会变，且有有效时间
     * </pre>
     *
     * <code>optional string access_token = 2;</code>
     */
    boolean hasAccessToken();
    /**
     * <pre>
     * 业务明文传输的一个标识用户在这台设备验证了登录信息的token，每次登录都会变，且有有效时间
     * </pre>
     *
     * <code>optional string access_token = 2;</code>
     */
    String getAccessToken();
    /**
     * <pre>
     * 业务明文传输的一个标识用户在这台设备验证了登录信息的token，每次登录都会变，且有有效时间
     * </pre>
     *
     * <code>optional string access_token = 2;</code>
     */
    com.google.protobuf.ByteString
        getAccessTokenBytes();

    /**
     * <pre>
     * 请求序列，用于服务端内部通信使用，与客户端无关
     * </pre>
     *
     * <code>optional sint32 seq = 3;</code>
     */
    boolean hasSeq();
    /**
     * <pre>
     * 请求序列，用于服务端内部通信使用，与客户端无关
     * </pre>
     *
     * <code>optional sint32 seq = 3;</code>
     */
    int getSeq();
  }
  /**
   * Protobuf type {@code Request}
   */
  public  static final class Request extends
      com.google.protobuf.GeneratedMessageV3.ExtendableMessage<
        Request> implements
      // @@protoc_insertion_point(message_implements:Request)
      RequestOrBuilder {
    // Use Request.newBuilder() to construct.
    private Request(ExtendableBuilder<Request, ?> builder) {
      super(builder);
    }
    private Request() {
      requestType_ = 0;
      accessToken_ = "";
      seq_ = 0;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Request(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              RequestType value = RequestType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                requestType_ = rawValue;
              }
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              accessToken_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              seq_ = input.readSInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return BusinessMsg.internal_static_Request_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return BusinessMsg.internal_static_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Request.class, Builder.class);
    }

    private int bitField0_;
    public static final int REQUEST_TYPE_FIELD_NUMBER = 1;
    private int requestType_;
    /**
     * <code>optional .RequestType request_type = 1;</code>
     */
    public boolean hasRequestType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .RequestType request_type = 1;</code>
     */
    public RequestType getRequestType() {
      RequestType result = RequestType.valueOf(requestType_);
      return result == null ? RequestType.REQUEST_LOGIN : result;
    }

    public static final int ACCESS_TOKEN_FIELD_NUMBER = 2;
    private volatile Object accessToken_;
    /**
     * <pre>
     * 业务明文传输的一个标识用户在这台设备验证了登录信息的token，每次登录都会变，且有有效时间
     * </pre>
     *
     * <code>optional string access_token = 2;</code>
     */
    public boolean hasAccessToken() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     * 业务明文传输的一个标识用户在这台设备验证了登录信息的token，每次登录都会变，且有有效时间
     * </pre>
     *
     * <code>optional string access_token = 2;</code>
     */
    public String getAccessToken() {
      Object ref = accessToken_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          accessToken_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * 业务明文传输的一个标识用户在这台设备验证了登录信息的token，每次登录都会变，且有有效时间
     * </pre>
     *
     * <code>optional string access_token = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAccessTokenBytes() {
      Object ref = accessToken_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        accessToken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SEQ_FIELD_NUMBER = 3;
    private int seq_;
    /**
     * <pre>
     * 请求序列，用于服务端内部通信使用，与客户端无关
     * </pre>
     *
     * <code>optional sint32 seq = 3;</code>
     */
    public boolean hasSeq() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <pre>
     * 请求序列，用于服务端内部通信使用，与客户端无关
     * </pre>
     *
     * <code>optional sint32 seq = 3;</code>
     */
    public int getSeq() {
      return seq_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!extensionsAreInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      ExtensionWriter
          extensionWriter = newExtensionWriter();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, requestType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, accessToken_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeSInt32(3, seq_);
      }
      extensionWriter.writeUntil(536870912, output);
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, requestType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, accessToken_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(3, seq_);
      }
      size += extensionsSerializedSize();
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Request)) {
        return super.equals(obj);
      }
      Request other = (Request) obj;

      boolean result = true;
      result = result && (hasRequestType() == other.hasRequestType());
      if (hasRequestType()) {
        result = result && requestType_ == other.requestType_;
      }
      result = result && (hasAccessToken() == other.hasAccessToken());
      if (hasAccessToken()) {
        result = result && getAccessToken()
            .equals(other.getAccessToken());
      }
      result = result && (hasSeq() == other.hasSeq());
      if (hasSeq()) {
        result = result && (getSeq()
            == other.getSeq());
      }
      result = result && unknownFields.equals(other.unknownFields);
      result = result &&
          getExtensionFields().equals(other.getExtensionFields());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasRequestType()) {
        hash = (37 * hash) + REQUEST_TYPE_FIELD_NUMBER;
        hash = (53 * hash) + requestType_;
      }
      if (hasAccessToken()) {
        hash = (37 * hash) + ACCESS_TOKEN_FIELD_NUMBER;
        hash = (53 * hash) + getAccessToken().hashCode();
      }
      if (hasSeq()) {
        hash = (37 * hash) + SEQ_FIELD_NUMBER;
        hash = (53 * hash) + getSeq();
      }
      hash = hashFields(hash, getExtensionFields());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Request prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Request}
     */
    public static final class Builder extends
        ExtendableBuilder<
          Request, Builder> implements
        // @@protoc_insertion_point(builder_implements:Request)
        RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return BusinessMsg.internal_static_Request_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return BusinessMsg.internal_static_Request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Request.class, Builder.class);
      }

      // Construct using cn.zjnktion.richer.core.protobuf.BusinessMsg.Request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        requestType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        accessToken_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        seq_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return BusinessMsg.internal_static_Request_descriptor;
      }

      public Request getDefaultInstanceForType() {
        return Request.getDefaultInstance();
      }

      public Request build() {
        Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Request buildPartial() {
        Request result = new Request(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.requestType_ = requestType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.accessToken_ = accessToken_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.seq_ = seq_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public <Type> Builder setExtension(
          com.google.protobuf.GeneratedMessage.GeneratedExtension<
              Request, Type> extension,
          Type value) {
        return (Builder) super.setExtension(extension, value);
      }
      public <Type> Builder setExtension(
          com.google.protobuf.GeneratedMessage.GeneratedExtension<
              Request, java.util.List<Type>> extension,
          int index, Type value) {
        return (Builder) super.setExtension(extension, index, value);
      }
      public <Type> Builder addExtension(
          com.google.protobuf.GeneratedMessage.GeneratedExtension<
              Request, java.util.List<Type>> extension,
          Type value) {
        return (Builder) super.addExtension(extension, value);
      }
      public <Type> Builder clearExtension(
          com.google.protobuf.GeneratedMessage.GeneratedExtension<
              Request, ?> extension) {
        return (Builder) super.clearExtension(extension);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Request) {
          return mergeFrom((Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Request other) {
        if (other == Request.getDefaultInstance()) return this;
        if (other.hasRequestType()) {
          setRequestType(other.getRequestType());
        }
        if (other.hasAccessToken()) {
          bitField0_ |= 0x00000002;
          accessToken_ = other.accessToken_;
          onChanged();
        }
        if (other.hasSeq()) {
          setSeq(other.getSeq());
        }
        this.mergeExtensionFields(other);
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!extensionsAreInitialized()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Request parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Request) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int requestType_ = 0;
      /**
       * <code>optional .RequestType request_type = 1;</code>
       */
      public boolean hasRequestType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .RequestType request_type = 1;</code>
       */
      public RequestType getRequestType() {
        RequestType result = RequestType.valueOf(requestType_);
        return result == null ? RequestType.REQUEST_LOGIN : result;
      }
      /**
       * <code>optional .RequestType request_type = 1;</code>
       */
      public Builder setRequestType(RequestType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        requestType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .RequestType request_type = 1;</code>
       */
      public Builder clearRequestType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        requestType_ = 0;
        onChanged();
        return this;
      }

      private Object accessToken_ = "";
      /**
       * <pre>
       * 业务明文传输的一个标识用户在这台设备验证了登录信息的token，每次登录都会变，且有有效时间
       * </pre>
       *
       * <code>optional string access_token = 2;</code>
       */
      public boolean hasAccessToken() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <pre>
       * 业务明文传输的一个标识用户在这台设备验证了登录信息的token，每次登录都会变，且有有效时间
       * </pre>
       *
       * <code>optional string access_token = 2;</code>
       */
      public String getAccessToken() {
        Object ref = accessToken_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            accessToken_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 业务明文传输的一个标识用户在这台设备验证了登录信息的token，每次登录都会变，且有有效时间
       * </pre>
       *
       * <code>optional string access_token = 2;</code>
       */
      public com.google.protobuf.ByteString
          getAccessTokenBytes() {
        Object ref = accessToken_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          accessToken_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 业务明文传输的一个标识用户在这台设备验证了登录信息的token，每次登录都会变，且有有效时间
       * </pre>
       *
       * <code>optional string access_token = 2;</code>
       */
      public Builder setAccessToken(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        accessToken_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 业务明文传输的一个标识用户在这台设备验证了登录信息的token，每次登录都会变，且有有效时间
       * </pre>
       *
       * <code>optional string access_token = 2;</code>
       */
      public Builder clearAccessToken() {
        bitField0_ = (bitField0_ & ~0x00000002);
        accessToken_ = getDefaultInstance().getAccessToken();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 业务明文传输的一个标识用户在这台设备验证了登录信息的token，每次登录都会变，且有有效时间
       * </pre>
       *
       * <code>optional string access_token = 2;</code>
       */
      public Builder setAccessTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        accessToken_ = value;
        onChanged();
        return this;
      }

      private int seq_ ;
      /**
       * <pre>
       * 请求序列，用于服务端内部通信使用，与客户端无关
       * </pre>
       *
       * <code>optional sint32 seq = 3;</code>
       */
      public boolean hasSeq() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <pre>
       * 请求序列，用于服务端内部通信使用，与客户端无关
       * </pre>
       *
       * <code>optional sint32 seq = 3;</code>
       */
      public int getSeq() {
        return seq_;
      }
      /**
       * <pre>
       * 请求序列，用于服务端内部通信使用，与客户端无关
       * </pre>
       *
       * <code>optional sint32 seq = 3;</code>
       */
      public Builder setSeq(int value) {
        bitField0_ |= 0x00000004;
        seq_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 请求序列，用于服务端内部通信使用，与客户端无关
       * </pre>
       *
       * <code>optional sint32 seq = 3;</code>
       */
      public Builder clearSeq() {
        bitField0_ = (bitField0_ & ~0x00000004);
        seq_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Request)
    }

    // @@protoc_insertion_point(class_scope:Request)
    private static final Request DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Request();
    }

    public static Request getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<Request>
        PARSER = new com.google.protobuf.AbstractParser<Request>() {
      public Request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Request(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Request> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Request> getParserForType() {
      return PARSER;
    }

    public Request getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Response)
      com.google.protobuf.GeneratedMessageV3.
          ExtendableMessageOrBuilder<Response> {

    /**
     * <code>optional .ResponseType response_type = 1;</code>
     */
    boolean hasResponseType();
    /**
     * <code>optional .ResponseType response_type = 1;</code>
     */
    ResponseType getResponseType();

    /**
     * <pre>
     * 请求时候用的token
     * </pre>
     *
     * <code>optional string access_token = 2;</code>
     */
    boolean hasAccessToken();
    /**
     * <pre>
     * 请求时候用的token
     * </pre>
     *
     * <code>optional string access_token = 2;</code>
     */
    String getAccessToken();
    /**
     * <pre>
     * 请求时候用的token
     * </pre>
     *
     * <code>optional string access_token = 2;</code>
     */
    com.google.protobuf.ByteString
        getAccessTokenBytes();

    /**
     * <pre>
     * 200=请求成功，404=非法请求，连接被断开。。。等等,详情查看对照表
     * </pre>
     *
     * <code>optional int32 code = 3;</code>
     */
    boolean hasCode();
    /**
     * <pre>
     * 200=请求成功，404=非法请求，连接被断开。。。等等,详情查看对照表
     * </pre>
     *
     * <code>optional int32 code = 3;</code>
     */
    int getCode();

    /**
     * <pre>
     * 响应序列，与请求序列对应
     * </pre>
     *
     * <code>optional sint32 seq = 4;</code>
     */
    boolean hasSeq();
    /**
     * <pre>
     * 响应序列，与请求序列对应
     * </pre>
     *
     * <code>optional sint32 seq = 4;</code>
     */
    int getSeq();
  }
  /**
   * Protobuf type {@code Response}
   */
  public  static final class Response extends
      com.google.protobuf.GeneratedMessageV3.ExtendableMessage<
        Response> implements
      // @@protoc_insertion_point(message_implements:Response)
      ResponseOrBuilder {
    // Use Response.newBuilder() to construct.
    private Response(ExtendableBuilder<Response, ?> builder) {
      super(builder);
    }
    private Response() {
      responseType_ = 0;
      accessToken_ = "";
      code_ = 0;
      seq_ = 0;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Response(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              ResponseType value = ResponseType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                responseType_ = rawValue;
              }
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              accessToken_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              code_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              seq_ = input.readSInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return BusinessMsg.internal_static_Response_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return BusinessMsg.internal_static_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Response.class, Builder.class);
    }

    private int bitField0_;
    public static final int RESPONSE_TYPE_FIELD_NUMBER = 1;
    private int responseType_;
    /**
     * <code>optional .ResponseType response_type = 1;</code>
     */
    public boolean hasResponseType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .ResponseType response_type = 1;</code>
     */
    public ResponseType getResponseType() {
      ResponseType result = ResponseType.valueOf(responseType_);
      return result == null ? ResponseType.RESPONSE_LOGIN : result;
    }

    public static final int ACCESS_TOKEN_FIELD_NUMBER = 2;
    private volatile Object accessToken_;
    /**
     * <pre>
     * 请求时候用的token
     * </pre>
     *
     * <code>optional string access_token = 2;</code>
     */
    public boolean hasAccessToken() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     * 请求时候用的token
     * </pre>
     *
     * <code>optional string access_token = 2;</code>
     */
    public String getAccessToken() {
      Object ref = accessToken_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          accessToken_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * 请求时候用的token
     * </pre>
     *
     * <code>optional string access_token = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAccessTokenBytes() {
      Object ref = accessToken_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        accessToken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CODE_FIELD_NUMBER = 3;
    private int code_;
    /**
     * <pre>
     * 200=请求成功，404=非法请求，连接被断开。。。等等,详情查看对照表
     * </pre>
     *
     * <code>optional int32 code = 3;</code>
     */
    public boolean hasCode() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <pre>
     * 200=请求成功，404=非法请求，连接被断开。。。等等,详情查看对照表
     * </pre>
     *
     * <code>optional int32 code = 3;</code>
     */
    public int getCode() {
      return code_;
    }

    public static final int SEQ_FIELD_NUMBER = 4;
    private int seq_;
    /**
     * <pre>
     * 响应序列，与请求序列对应
     * </pre>
     *
     * <code>optional sint32 seq = 4;</code>
     */
    public boolean hasSeq() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <pre>
     * 响应序列，与请求序列对应
     * </pre>
     *
     * <code>optional sint32 seq = 4;</code>
     */
    public int getSeq() {
      return seq_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!extensionsAreInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      ExtensionWriter
          extensionWriter = newExtensionWriter();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, responseType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, accessToken_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, code_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeSInt32(4, seq_);
      }
      extensionWriter.writeUntil(536870912, output);
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, responseType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, accessToken_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, code_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(4, seq_);
      }
      size += extensionsSerializedSize();
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Response)) {
        return super.equals(obj);
      }
      Response other = (Response) obj;

      boolean result = true;
      result = result && (hasResponseType() == other.hasResponseType());
      if (hasResponseType()) {
        result = result && responseType_ == other.responseType_;
      }
      result = result && (hasAccessToken() == other.hasAccessToken());
      if (hasAccessToken()) {
        result = result && getAccessToken()
            .equals(other.getAccessToken());
      }
      result = result && (hasCode() == other.hasCode());
      if (hasCode()) {
        result = result && (getCode()
            == other.getCode());
      }
      result = result && (hasSeq() == other.hasSeq());
      if (hasSeq()) {
        result = result && (getSeq()
            == other.getSeq());
      }
      result = result && unknownFields.equals(other.unknownFields);
      result = result &&
          getExtensionFields().equals(other.getExtensionFields());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasResponseType()) {
        hash = (37 * hash) + RESPONSE_TYPE_FIELD_NUMBER;
        hash = (53 * hash) + responseType_;
      }
      if (hasAccessToken()) {
        hash = (37 * hash) + ACCESS_TOKEN_FIELD_NUMBER;
        hash = (53 * hash) + getAccessToken().hashCode();
      }
      if (hasCode()) {
        hash = (37 * hash) + CODE_FIELD_NUMBER;
        hash = (53 * hash) + getCode();
      }
      if (hasSeq()) {
        hash = (37 * hash) + SEQ_FIELD_NUMBER;
        hash = (53 * hash) + getSeq();
      }
      hash = hashFields(hash, getExtensionFields());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Response prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Response}
     */
    public static final class Builder extends
        ExtendableBuilder<
          Response, Builder> implements
        // @@protoc_insertion_point(builder_implements:Response)
        ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return BusinessMsg.internal_static_Response_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return BusinessMsg.internal_static_Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Response.class, Builder.class);
      }

      // Construct using cn.zjnktion.richer.core.protobuf.BusinessMsg.Response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        responseType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        accessToken_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        code_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        seq_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return BusinessMsg.internal_static_Response_descriptor;
      }

      public Response getDefaultInstanceForType() {
        return Response.getDefaultInstance();
      }

      public Response build() {
        Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Response buildPartial() {
        Response result = new Response(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.responseType_ = responseType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.accessToken_ = accessToken_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.code_ = code_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.seq_ = seq_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public <Type> Builder setExtension(
          com.google.protobuf.GeneratedMessage.GeneratedExtension<
              Response, Type> extension,
          Type value) {
        return (Builder) super.setExtension(extension, value);
      }
      public <Type> Builder setExtension(
          com.google.protobuf.GeneratedMessage.GeneratedExtension<
              Response, java.util.List<Type>> extension,
          int index, Type value) {
        return (Builder) super.setExtension(extension, index, value);
      }
      public <Type> Builder addExtension(
          com.google.protobuf.GeneratedMessage.GeneratedExtension<
              Response, java.util.List<Type>> extension,
          Type value) {
        return (Builder) super.addExtension(extension, value);
      }
      public <Type> Builder clearExtension(
          com.google.protobuf.GeneratedMessage.GeneratedExtension<
              Response, ?> extension) {
        return (Builder) super.clearExtension(extension);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Response) {
          return mergeFrom((Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Response other) {
        if (other == Response.getDefaultInstance()) return this;
        if (other.hasResponseType()) {
          setResponseType(other.getResponseType());
        }
        if (other.hasAccessToken()) {
          bitField0_ |= 0x00000002;
          accessToken_ = other.accessToken_;
          onChanged();
        }
        if (other.hasCode()) {
          setCode(other.getCode());
        }
        if (other.hasSeq()) {
          setSeq(other.getSeq());
        }
        this.mergeExtensionFields(other);
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!extensionsAreInitialized()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Response parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Response) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int responseType_ = 0;
      /**
       * <code>optional .ResponseType response_type = 1;</code>
       */
      public boolean hasResponseType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .ResponseType response_type = 1;</code>
       */
      public ResponseType getResponseType() {
        ResponseType result = ResponseType.valueOf(responseType_);
        return result == null ? ResponseType.RESPONSE_LOGIN : result;
      }
      /**
       * <code>optional .ResponseType response_type = 1;</code>
       */
      public Builder setResponseType(ResponseType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        responseType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .ResponseType response_type = 1;</code>
       */
      public Builder clearResponseType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        responseType_ = 0;
        onChanged();
        return this;
      }

      private Object accessToken_ = "";
      /**
       * <pre>
       * 请求时候用的token
       * </pre>
       *
       * <code>optional string access_token = 2;</code>
       */
      public boolean hasAccessToken() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <pre>
       * 请求时候用的token
       * </pre>
       *
       * <code>optional string access_token = 2;</code>
       */
      public String getAccessToken() {
        Object ref = accessToken_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            accessToken_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 请求时候用的token
       * </pre>
       *
       * <code>optional string access_token = 2;</code>
       */
      public com.google.protobuf.ByteString
          getAccessTokenBytes() {
        Object ref = accessToken_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          accessToken_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 请求时候用的token
       * </pre>
       *
       * <code>optional string access_token = 2;</code>
       */
      public Builder setAccessToken(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        accessToken_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 请求时候用的token
       * </pre>
       *
       * <code>optional string access_token = 2;</code>
       */
      public Builder clearAccessToken() {
        bitField0_ = (bitField0_ & ~0x00000002);
        accessToken_ = getDefaultInstance().getAccessToken();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 请求时候用的token
       * </pre>
       *
       * <code>optional string access_token = 2;</code>
       */
      public Builder setAccessTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        accessToken_ = value;
        onChanged();
        return this;
      }

      private int code_ ;
      /**
       * <pre>
       * 200=请求成功，404=非法请求，连接被断开。。。等等,详情查看对照表
       * </pre>
       *
       * <code>optional int32 code = 3;</code>
       */
      public boolean hasCode() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <pre>
       * 200=请求成功，404=非法请求，连接被断开。。。等等,详情查看对照表
       * </pre>
       *
       * <code>optional int32 code = 3;</code>
       */
      public int getCode() {
        return code_;
      }
      /**
       * <pre>
       * 200=请求成功，404=非法请求，连接被断开。。。等等,详情查看对照表
       * </pre>
       *
       * <code>optional int32 code = 3;</code>
       */
      public Builder setCode(int value) {
        bitField0_ |= 0x00000004;
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 200=请求成功，404=非法请求，连接被断开。。。等等,详情查看对照表
       * </pre>
       *
       * <code>optional int32 code = 3;</code>
       */
      public Builder clearCode() {
        bitField0_ = (bitField0_ & ~0x00000004);
        code_ = 0;
        onChanged();
        return this;
      }

      private int seq_ ;
      /**
       * <pre>
       * 响应序列，与请求序列对应
       * </pre>
       *
       * <code>optional sint32 seq = 4;</code>
       */
      public boolean hasSeq() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <pre>
       * 响应序列，与请求序列对应
       * </pre>
       *
       * <code>optional sint32 seq = 4;</code>
       */
      public int getSeq() {
        return seq_;
      }
      /**
       * <pre>
       * 响应序列，与请求序列对应
       * </pre>
       *
       * <code>optional sint32 seq = 4;</code>
       */
      public Builder setSeq(int value) {
        bitField0_ |= 0x00000008;
        seq_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 响应序列，与请求序列对应
       * </pre>
       *
       * <code>optional sint32 seq = 4;</code>
       */
      public Builder clearSeq() {
        bitField0_ = (bitField0_ & ~0x00000008);
        seq_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Response)
    }

    // @@protoc_insertion_point(class_scope:Response)
    private static final Response DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Response();
    }

    public static Response getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<Response>
        PARSER = new com.google.protobuf.AbstractParser<Response>() {
      public Response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Response(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Response> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Response> getParserForType() {
      return PARSER;
    }

    public Response getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Request_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Request_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Response_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\030richer/BusinessMsg.proto\"Z\n\007Request\022\"\n" +
      "\014request_type\030\001 \001(\0162\014.RequestType\022\024\n\014acc" +
      "ess_token\030\002 \001(\t\022\013\n\003seq\030\003 \001(\021*\010\010d\020\200\200\200\200\002\"k" +
      "\n\010Response\022$\n\rresponse_type\030\001 \001(\0162\r.Resp" +
      "onseType\022\024\n\014access_token\030\002 \001(\t\022\014\n\004code\030\003" +
      " \001(\005\022\013\n\003seq\030\004 \001(\021*\010\010d\020\200\200\200\200\002*a\n\013RequestTy" +
      "pe\022\021\n\rREQUEST_LOGIN\020\000\022\024\n\020REQUEST_REGISTE" +
      "R\020\001\022\025\n\021REQUEST_HEARTBEAT\020\002\022\022\n\016REQUEST_LO" +
      "GOUT\020\003*\204\001\n\014ResponseType\022\022\n\016RESPONSE_LOGI" +
      "N\020\000\022\025\n\021RESPONSE_REGISTER\020\001\022\026\n\022RESPONSE_H",
      "EARTBEAT\020\002\022\023\n\017RESPONSE_LOGOUT\020\003\022\034\n\030RESPO" +
      "NSE_DUPLICATE_LOGIN\020\004B\"\n cn.zjnktion.ric" +
      "her.core.protobuf"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Request_descriptor,
        new String[] { "RequestType", "AccessToken", "Seq", });
    internal_static_Response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Response_descriptor,
        new String[] { "ResponseType", "AccessToken", "Code", "Seq", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
