// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: richer/GateResponseMsg.proto

package cn.zjnktion.richer.core.protobuf;

public final class GateResponseMsg {
  private GateResponseMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GateResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GateResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string latest_version = 1;</code>
     */
    String getLatestVersion();
    /**
     * <code>optional string latest_version = 1;</code>
     */
    com.google.protobuf.ByteString
        getLatestVersionBytes();

    /**
     * <code>optional bool need_update = 2;</code>
     */
    boolean getNeedUpdate();

    /**
     * <code>optional string update_url = 3;</code>
     */
    String getUpdateUrl();
    /**
     * <code>optional string update_url = 3;</code>
     */
    com.google.protobuf.ByteString
        getUpdateUrlBytes();

    /**
     * <code>optional string server_ip = 4;</code>
     */
    String getServerIp();
    /**
     * <code>optional string server_ip = 4;</code>
     */
    com.google.protobuf.ByteString
        getServerIpBytes();

    /**
     * <code>optional int32 server_port = 5;</code>
     */
    int getServerPort();
  }
  /**
   * Protobuf type {@code GateResponse}
   */
  public  static final class GateResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:GateResponse)
      GateResponseOrBuilder {
    // Use GateResponse.newBuilder() to construct.
    private GateResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GateResponse() {
      latestVersion_ = "";
      needUpdate_ = false;
      updateUrl_ = "";
      serverIp_ = "";
      serverPort_ = 0;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private GateResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readStringRequireUtf8();

              latestVersion_ = s;
              break;
            }
            case 16: {

              needUpdate_ = input.readBool();
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              updateUrl_ = s;
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              serverIp_ = s;
              break;
            }
            case 40: {

              serverPort_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GateResponseMsg.internal_static_GateResponse_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GateResponseMsg.internal_static_GateResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              GateResponse.class, Builder.class);
    }

    public static final int LATEST_VERSION_FIELD_NUMBER = 1;
    private volatile Object latestVersion_;
    /**
     * <code>optional string latest_version = 1;</code>
     */
    public String getLatestVersion() {
      Object ref = latestVersion_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        latestVersion_ = s;
        return s;
      }
    }
    /**
     * <code>optional string latest_version = 1;</code>
     */
    public com.google.protobuf.ByteString
        getLatestVersionBytes() {
      Object ref = latestVersion_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        latestVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NEED_UPDATE_FIELD_NUMBER = 2;
    private boolean needUpdate_;
    /**
     * <code>optional bool need_update = 2;</code>
     */
    public boolean getNeedUpdate() {
      return needUpdate_;
    }

    public static final int UPDATE_URL_FIELD_NUMBER = 3;
    private volatile Object updateUrl_;
    /**
     * <code>optional string update_url = 3;</code>
     */
    public String getUpdateUrl() {
      Object ref = updateUrl_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        updateUrl_ = s;
        return s;
      }
    }
    /**
     * <code>optional string update_url = 3;</code>
     */
    public com.google.protobuf.ByteString
        getUpdateUrlBytes() {
      Object ref = updateUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        updateUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SERVER_IP_FIELD_NUMBER = 4;
    private volatile Object serverIp_;
    /**
     * <code>optional string server_ip = 4;</code>
     */
    public String getServerIp() {
      Object ref = serverIp_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        serverIp_ = s;
        return s;
      }
    }
    /**
     * <code>optional string server_ip = 4;</code>
     */
    public com.google.protobuf.ByteString
        getServerIpBytes() {
      Object ref = serverIp_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        serverIp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SERVER_PORT_FIELD_NUMBER = 5;
    private int serverPort_;
    /**
     * <code>optional int32 server_port = 5;</code>
     */
    public int getServerPort() {
      return serverPort_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getLatestVersionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, latestVersion_);
      }
      if (needUpdate_ != false) {
        output.writeBool(2, needUpdate_);
      }
      if (!getUpdateUrlBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, updateUrl_);
      }
      if (!getServerIpBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, serverIp_);
      }
      if (serverPort_ != 0) {
        output.writeInt32(5, serverPort_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getLatestVersionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, latestVersion_);
      }
      if (needUpdate_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, needUpdate_);
      }
      if (!getUpdateUrlBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, updateUrl_);
      }
      if (!getServerIpBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, serverIp_);
      }
      if (serverPort_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, serverPort_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof GateResponse)) {
        return super.equals(obj);
      }
      GateResponse other = (GateResponse) obj;

      boolean result = true;
      result = result && getLatestVersion()
          .equals(other.getLatestVersion());
      result = result && (getNeedUpdate()
          == other.getNeedUpdate());
      result = result && getUpdateUrl()
          .equals(other.getUpdateUrl());
      result = result && getServerIp()
          .equals(other.getServerIp());
      result = result && (getServerPort()
          == other.getServerPort());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + LATEST_VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getLatestVersion().hashCode();
      hash = (37 * hash) + NEED_UPDATE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getNeedUpdate());
      hash = (37 * hash) + UPDATE_URL_FIELD_NUMBER;
      hash = (53 * hash) + getUpdateUrl().hashCode();
      hash = (37 * hash) + SERVER_IP_FIELD_NUMBER;
      hash = (53 * hash) + getServerIp().hashCode();
      hash = (37 * hash) + SERVER_PORT_FIELD_NUMBER;
      hash = (53 * hash) + getServerPort();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static GateResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GateResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GateResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GateResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GateResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GateResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static GateResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static GateResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static GateResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GateResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(GateResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GateResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GateResponse)
        GateResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return GateResponseMsg.internal_static_GateResponse_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return GateResponseMsg.internal_static_GateResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                GateResponse.class, Builder.class);
      }

      // Construct using cn.zjnktion.richer.core.protobuf.GateResponseMsg.GateResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        latestVersion_ = "";

        needUpdate_ = false;

        updateUrl_ = "";

        serverIp_ = "";

        serverPort_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return GateResponseMsg.internal_static_GateResponse_descriptor;
      }

      public GateResponse getDefaultInstanceForType() {
        return GateResponse.getDefaultInstance();
      }

      public GateResponse build() {
        GateResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public GateResponse buildPartial() {
        GateResponse result = new GateResponse(this);
        result.latestVersion_ = latestVersion_;
        result.needUpdate_ = needUpdate_;
        result.updateUrl_ = updateUrl_;
        result.serverIp_ = serverIp_;
        result.serverPort_ = serverPort_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof GateResponse) {
          return mergeFrom((GateResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(GateResponse other) {
        if (other == GateResponse.getDefaultInstance()) return this;
        if (!other.getLatestVersion().isEmpty()) {
          latestVersion_ = other.latestVersion_;
          onChanged();
        }
        if (other.getNeedUpdate() != false) {
          setNeedUpdate(other.getNeedUpdate());
        }
        if (!other.getUpdateUrl().isEmpty()) {
          updateUrl_ = other.updateUrl_;
          onChanged();
        }
        if (!other.getServerIp().isEmpty()) {
          serverIp_ = other.serverIp_;
          onChanged();
        }
        if (other.getServerPort() != 0) {
          setServerPort(other.getServerPort());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        GateResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (GateResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object latestVersion_ = "";
      /**
       * <code>optional string latest_version = 1;</code>
       */
      public String getLatestVersion() {
        Object ref = latestVersion_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          latestVersion_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string latest_version = 1;</code>
       */
      public com.google.protobuf.ByteString
          getLatestVersionBytes() {
        Object ref = latestVersion_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          latestVersion_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string latest_version = 1;</code>
       */
      public Builder setLatestVersion(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        latestVersion_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string latest_version = 1;</code>
       */
      public Builder clearLatestVersion() {
        
        latestVersion_ = getDefaultInstance().getLatestVersion();
        onChanged();
        return this;
      }
      /**
       * <code>optional string latest_version = 1;</code>
       */
      public Builder setLatestVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        latestVersion_ = value;
        onChanged();
        return this;
      }

      private boolean needUpdate_ ;
      /**
       * <code>optional bool need_update = 2;</code>
       */
      public boolean getNeedUpdate() {
        return needUpdate_;
      }
      /**
       * <code>optional bool need_update = 2;</code>
       */
      public Builder setNeedUpdate(boolean value) {
        
        needUpdate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool need_update = 2;</code>
       */
      public Builder clearNeedUpdate() {
        
        needUpdate_ = false;
        onChanged();
        return this;
      }

      private Object updateUrl_ = "";
      /**
       * <code>optional string update_url = 3;</code>
       */
      public String getUpdateUrl() {
        Object ref = updateUrl_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          updateUrl_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string update_url = 3;</code>
       */
      public com.google.protobuf.ByteString
          getUpdateUrlBytes() {
        Object ref = updateUrl_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          updateUrl_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string update_url = 3;</code>
       */
      public Builder setUpdateUrl(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        updateUrl_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string update_url = 3;</code>
       */
      public Builder clearUpdateUrl() {
        
        updateUrl_ = getDefaultInstance().getUpdateUrl();
        onChanged();
        return this;
      }
      /**
       * <code>optional string update_url = 3;</code>
       */
      public Builder setUpdateUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        updateUrl_ = value;
        onChanged();
        return this;
      }

      private Object serverIp_ = "";
      /**
       * <code>optional string server_ip = 4;</code>
       */
      public String getServerIp() {
        Object ref = serverIp_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          serverIp_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string server_ip = 4;</code>
       */
      public com.google.protobuf.ByteString
          getServerIpBytes() {
        Object ref = serverIp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          serverIp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string server_ip = 4;</code>
       */
      public Builder setServerIp(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        serverIp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string server_ip = 4;</code>
       */
      public Builder clearServerIp() {
        
        serverIp_ = getDefaultInstance().getServerIp();
        onChanged();
        return this;
      }
      /**
       * <code>optional string server_ip = 4;</code>
       */
      public Builder setServerIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        serverIp_ = value;
        onChanged();
        return this;
      }

      private int serverPort_ ;
      /**
       * <code>optional int32 server_port = 5;</code>
       */
      public int getServerPort() {
        return serverPort_;
      }
      /**
       * <code>optional int32 server_port = 5;</code>
       */
      public Builder setServerPort(int value) {
        
        serverPort_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 server_port = 5;</code>
       */
      public Builder clearServerPort() {
        
        serverPort_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:GateResponse)
    }

    // @@protoc_insertion_point(class_scope:GateResponse)
    private static final GateResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new GateResponse();
    }

    public static GateResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GateResponse>
        PARSER = new com.google.protobuf.AbstractParser<GateResponse>() {
      public GateResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new GateResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GateResponse> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<GateResponse> getParserForType() {
      return PARSER;
    }

    public GateResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GateResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GateResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\034richer/GateResponseMsg.proto\"w\n\014GateRe" +
      "sponse\022\026\n\016latest_version\030\001 \001(\t\022\023\n\013need_u" +
      "pdate\030\002 \001(\010\022\022\n\nupdate_url\030\003 \001(\t\022\021\n\tserve" +
      "r_ip\030\004 \001(\t\022\023\n\013server_port\030\005 \001(\005B\"\n cn.zj" +
      "nktion.richer.core.protobufb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_GateResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GateResponse_descriptor,
        new String[] { "LatestVersion", "NeedUpdate", "UpdateUrl", "ServerIp", "ServerPort", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
